[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fyno"
dynamic = ["version"]
description = "A lightweight personal workbench."
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
keywords = ["workbench", "tools", "markdown"]
authors = [
  { name = "aikwen", email = "kwen.zou@outlook.com" },
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: Implementation :: CPython",
]
dependencies = []

[project.urls]
Documentation = "https://github.com/aikwen/fyno#readme"
Issues = "https://github.com/aikwen/fyno/issues"
Source = "https://github.com/aikwen/fyno"

[tool.hatch.version]
path = "src/fyno/__about__.py"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]

[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/fyno tests}"

[tool.coverage.run]
source_pkgs = ["fyno", "tests"]
branch = true
parallel = true
omit = [
  "src/fyno/__about__.py",
]

[tool.coverage.paths]
fyno = ["src/fyno", "*/fyno/src/fyno"]
tests = ["tests", "*/fyno/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]